INSERT INTO projects (id, title, category, funding_goal, start_date , end_date) VALUES ('Project 1', 'math', 100, 'May 2' , 'Sept 4')
INSERT INTO projects (id, title, category, funding_goal, start_date , end_date) VALUES ('Project 2', 'science', 200, 'May 2' , 'Sept 4')
INSERT INTO projects (id, title, category, funding_goal, start_date , end_date) VALUES ('Project 3', 'art', 100, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 4', 'english', 300, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 5', 'math', 200, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 6', 'science', 100, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 7', 'english', 400, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 8', 'art', 500, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 9', 'art', 400, 'May 2' , 'Sept 4')
INSERT INTO projects (title, category, funding_goal, start_date , end_date) VALUES ('Project 10', 'math', 100, 'May 2' , 'Sept 4')